//! `demo-apply.lua` text generator (TSK-405).
//!
//! Renders the temp-track-only Lua applier from the ranked demo candidates:
//! each candidate gets one independent undo block, the tail rolls all three
//! back in reverse order, and a cleanup block deletes the temp track. The
//! generator only formats text (no REAPER contact, no I/O); every ReaScript
//! call below is backed by repo evidence cited in the emitted comments
//! (`experiments/b-matrix-*.out.txt`, 2026-10-06).

/// One ranked candidate as the Lua applier needs it.
#[derive(Clone, Debug)]
pub struct LuaCandidate {
    /// Stable id (also the undo-block label suffix).
    pub id: String,
    /// Audible-difference sentence, shown in comments only.
    pub diff_zh: String,
    /// `(ident, normalized value)` pairs in application order.
    pub params: Vec<(String, f64)>,
}

/// Render `demo-apply.lua` for `seed`/`snapshot` and the ranked candidates.
///
/// The output is deterministic in its inputs (no timestamps, no absolute
/// paths); the script itself writes `demo-apply.out.txt` next to its own
/// location at run time.
#[must_use]
pub fn render(seed: u64, snapshot: &str, candidates: &[LuaCandidate]) -> String {
    let mut out = String::new();
    out.push_str("-- demo-apply.lua — generated by `acrd demo --seed ");
    out.push_str(&seed.to_string());
    out.push_str("` (TSK-405 M3 harness).\n");
    out.push_str("-- 诚实声明：候选来自固定种子确定性占位，非模型推理。\n");
    out.push_str("-- 安全：只操作本脚本新建的临时轨；全程不存盘；结束删除临时轨。\n");
    out.push_str("-- Undo 语义：\n");
    out.push_str("--   * 每个候选一个独立 undo 块 \"SynthLM demo: apply <id>\"\n");
    out.push_str(
        "--     （Undo_BeginBlock2/EndBlock2，extraflags -1 == UNDO_STATE_ALL，DEC-008）。\n",
    );
    out.push_str("--   * 末尾按逆序 DoUndo2 逐个回滚全部块；History 条目数不减少是正常的\n");
    out.push_str(
        "--     （undo 不删历史），断言依据是参数值回到快照（容差 1e-9），不是历史条数。\n",
    );
    out.push_str(
        "--   * 清理块 \"SynthLM demo: cleanup temp track\" 包裹删轨；删轨后轨数回到 ntr0。\n",
    );
    out.push_str("-- 运行：reaper.exe -nonewinst <本文件>；日志见同目录 demo-apply.out.txt。\n");
    out.push_str("local SEED = ");
    out.push_str(&seed.to_string());
    out.push_str("\nlocal SNAPSHOT = \"");
    out.push_str(&lua_escape(snapshot));
    out.push_str("\"\nlocal CANDIDATES = {\n");
    for candidate in candidates {
        out.push_str("  { id = \"");
        out.push_str(&lua_escape(&candidate.id));
        out.push_str("\", diff = \"");
        out.push_str(&lua_escape(&candidate.diff_zh));
        out.push_str("\", params = { ");
        for (index, (ident, value)) in candidate.params.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }
            out.push_str("{ \"");
            out.push_str(&lua_escape(ident));
            out.push_str("\", ");
            out.push_str(&format_lua_number(*value));
            out.push_str(" }");
        }
        out.push_str(" } },\n");
    }
    out.push_str("}\n");
    out.push_str(SCRIPT_BODY);
    out
}

/// Escape a string for a double-quoted Lua literal (defensive: demo strings
/// carry no quotes or backslashes, but the applier must never emit broken
/// syntax if a sentence ever gains one).
fn lua_escape(text: &str) -> String {
    let mut escaped = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

/// Format a normalized parameter value as a Lua number literal.
fn format_lua_number(value: f64) -> String {
    format!("{value:.6}")
}

/// Fixed applier body: resolve → snapshot → 3 apply blocks → rollback → cleanup.
const SCRIPT_BODY: &str = r#"local TOL = 1e-9
local base = debug.getinfo(1, "S").source:match("@?(.*[/\\])")
local out_path = base .. "demo-apply.out.txt"
local lines = {}
local function log(s) lines[#lines+1] = s end
local function flush()
  local f = io.open(out_path, "w")
  if f then f:write(table.concat(lines, "\n") .. "\n") f:close() end
end
local function fmt_val(v) return string.format("%.9f", v) end
local function run()
  reaper.PreventUIRefresh(1)
  local ntr0 = reaper.CountTracks(0)
  log("seed=" .. tostring(SEED) .. " snapshot=" .. SNAPSHOT .. " tracks_before=" .. tostring(ntr0))
  reaper.InsertTrackAtIndex(ntr0, false)
  local tr = reaper.GetTrack(0, ntr0)
  assert(tr, "temp track missing")
  -- ReaEQ：先查后建（instantiate 0 仅查询，-1000 新建；见 b-matrix-01-stock.lua:26）。
  local fx = reaper.TrackFX_AddByName(tr, "ReaEQ", false, 0)
  local fx_how = "query"
  if fx < 0 then fx = reaper.TrackFX_AddByName(tr, "ReaEQ", false, -1000) fx_how = "add" end
  log("fx=" .. tostring(fx) .. " via=" .. fx_how)
  assert(fx >= 0, "ReaEQ unavailable")
  -- ident→序号：优先 FromIdent（实测 bogus 返回 -1，见 b-matrix-02-ident-env.out.txt:7），
  -- 回退枚举 GetParamIdent 精确匹配；缺 API 时直接走枚举分支。
  local has_from_ident = type(reaper.TrackFX_GetParamFromIdent) == "function"
  local function resolve(ident)
    if has_from_ident then
      local idx = reaper.TrackFX_GetParamFromIdent(tr, fx, ident)
      if type(idx) == "number" and idx >= 0 then return idx, "from_ident" end
    end
    local n = reaper.TrackFX_GetNumParams(tr, fx)
    for i = 0, n - 1 do
      local ok, nm = reaper.TrackFX_GetParamIdent(tr, fx, i)
      if ok and nm == ident then return i, "enumerate" end
    end
    return nil, "missing"
  end
  -- 快照全部涉及参数的初值（只读，不开 undo 块）。
  local initial = {}
  for _, c in ipairs(CANDIDATES) do
    for _, p in ipairs(c.params) do
      if initial[p[1]] == nil then
        local idx, how = resolve(p[1])
        assert(idx ~= nil, "unresolvable ident " .. p[1])
        initial[p[1]] = { idx = idx, value = reaper.TrackFX_GetParam(tr, fx, idx), how = how }
        log("resolve|" .. p[1] .. "=" .. tostring(idx) .. "|" .. how .. "|init=" .. fmt_val(initial[p[1]].value))
      end
    end
  end
  flush()
  -- 依次应用：每候选独立 undo 块（对应 Rust 侧 bridge UndoBlock 一求解一 undo 点，DEC-008）。
  for _, c in ipairs(CANDIDATES) do
    reaper.Undo_BeginBlock2(0)
    for _, p in ipairs(c.params) do
      reaper.TrackFX_SetParam(tr, fx, initial[p[1]].idx, p[2])
    end
    reaper.Undo_EndBlock2(0, "SynthLM demo: apply " .. c.id, -1)
    local parts = {}
    for _, p in ipairs(c.params) do
      parts[#parts+1] = p[1] .. "=" .. fmt_val(reaper.TrackFX_GetParam(tr, fx, initial[p[1]].idx))
    end
    log("applied|" .. c.id .. "|" .. table.concat(parts, " "))
    flush()
  end
  -- 全部回滚：逆序 DoUndo2（3 块），然后断言每个参数回到初值。
  for i = #CANDIDATES, 1, -1 do
    reaper.Undo_DoUndo2(0)
    log("undo|" .. CANDIDATES[i].id)
  end
  local restored = true
  for ident, snap in pairs(initial) do
    local v = reaper.TrackFX_GetParam(tr, fx, snap.idx)
    local ok = math.abs(v - snap.value) < TOL
    restored = restored and ok
    log("restored|" .. ident .. "=" .. fmt_val(v) .. "|expect=" .. fmt_val(snap.value) .. "|ok=" .. tostring(ok))
  end
  log("restored_all=" .. tostring(restored))
  assert(restored, "rollback mismatch")
  flush()
  -- 清理：删临时轨（独立 cleanup 块），断言轨数归零。
  reaper.Undo_BeginBlock2(0)
  reaper.DeleteTrack(tr)
  reaper.Undo_EndBlock2(0, "SynthLM demo: cleanup temp track", -1)
  local ntr1 = reaper.CountTracks(0)
  log("tracks_after=" .. tostring(ntr1) .. "|tracks_zero=" .. tostring(ntr1 == ntr0))
  assert(ntr1 == ntr0, "temp track leaked")
  reaper.PreventUIRefresh(-1)
  reaper.UpdateArrange()
  log("demo_apply_ok=true")
end
local ok, err = xpcall(run, debug.traceback)
if not ok then
  log("FATAL=" .. tostring(err))
  pcall(function() reaper.PreventUIRefresh(-1) end)
end
flush()
"#;
