//! REAPER extension entry for the SynthLM bridge (TSK-114 smoke).
//!
//! This module turns `synthlm-bridge` into a loadable REAPER extension
//! (`cdylib`, see `crates/bridge/Cargo.toml`) while keeping the `rlib` target
//! for unit tests. The entry does exactly three things:
//!
//! 1. Logs the bridge version to the ReaScript console (desensitised: version
//!    string only, no absolute paths, per `AGENTS.md` §8).
//! 2. Registers one harmless test action (`SynthLM_TestPing`) whose only
//!    effect is writing a marker file into `%TEMP%`; it never touches the
//!    project, takes, FX, or undo state.
//! 3. Returns success so REAPER keeps the extension loaded; on REAPER exit the
//!    DLL unloads with no hooks left behind (clean unload).
//!
//! # Red lines (`AGENTS.md` §3)
//!
//! - Control plane only: main thread, never the audio thread. The action
//!   callback runs on REAPER's main thread (action dispatch), so the single
//!   `%TEMP%` file write is allowed there (the file-I/O ban covers the audio
//!   thread only).
//! - No third-party plug-in hosting/loading, no reverse engineering, no hooks,
//!   no patching. We only register our *own* command ID via the safe
//!   `reaper-medium` wrappers.
//!
//! # Upstream scaffold (reaper-rs rev `659b22b`, verified 2026-10-06)
//!
//! The canonical scaffold is the `reaper_extension_plugin` attribute macro
//! (`main/macros/src/lib.rs:47`, low-level branch `main/macros/src/lib.rs:72`
//! expanding at lines 82–95): it emits `reaper_low::dll_main!()` +
//! `reaper_low::swell_dll_main!()` plus
//! `unsafe extern "C" fn ReaperPluginEntry(h_instance, rec)` which forwards to
//! `reaper_low::bootstrap_extension_plugin` (`main/low/src/util.rs:34`). The
//! entry below is a line-for-line hand transcription of that expansion, so
//! `crates/bridge` needs **no** new `reaper-macros` dependency (same `MIT`
//! source already registered in `docs/LICENSES.md`). The project README
//! (`README.md:206`–`257`) documents the `cdylib` requirement, the
//! `ReaperPluginEntry → bootstrap_extension_plugin` wiring, the `reaper_`
//! file-prefix rule, and the `REAPER_RESOURCE_PATH/UserPlugins` load path
//! (loaded at REAPER start, hence a restart is required).
//!
//! Action registration uses `reaper-medium` only:
//! [`reaper_medium::ReaperSession::load`] (`main/medium/src/reaper_session.rs:138`),
//! [`reaper_medium::ReaperSession::plugin_register_add_command_id`] (`:560`),
//! [`reaper_medium::ReaperSession::plugin_register_add_gaccel`] (`:652`) with
//! [`reaper_medium::OwnedGaccelRegister::without_key_binding`]
//! (`main/medium/src/gaccel_register.rs:24`), and
//! [`reaper_medium::ReaperSession::plugin_register_add_hook_command`] (`:279`)
//! with [`reaper_medium::HookCommand`] (`main/medium/src/fn_traits.rs:13`).

use std::error::Error;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU32, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use reaper_low::PluginContext;
use reaper_medium::{CommandId, HookCommand, OwnedGaccelRegister, ReaperSession};

// ---------------------------------------------------------------------------
// Entry points (hand transcription of the `reaper_extension_plugin`
// low-level expansion; see module docs).
// ---------------------------------------------------------------------------

reaper_low::dll_main!();
reaper_low::swell_dll_main!();

/// REAPER extension entry point, called by REAPER at startup time.
///
/// Mirrors the function generated by `reaper_macros::reaper_extension_plugin`
/// for a one-argument `plugin_main` (`main/macros/src/lib.rs:82`–`:92`).
///
/// # Safety
///
/// (bridge-internal low encapsulation, `AGENTS.md` §4 unsafe 许可制)
///
/// - Precondition: REAPER calls this exactly once per load with the module
///   `HINSTANCE` and a pointer to its `reaper_plugin_info_t`. A null `rec`
///   is tolerated: [`reaper_low::bootstrap_extension_plugin`] checks for null
///   and returns `0`, which makes REAPER unload us cleanly.
/// - Invariant: no state is shared with the audio thread; `plugin_main` only
///   registers a main-thread command via safe `reaper-medium` wrappers.
/// - Caller obligation (REAPER): invoke on the main thread at load time, as it
///   does for every extension plug-in (e.g. SWS/ReaPack).
#[unsafe(no_mangle)]
unsafe extern "C" fn ReaperPluginEntry(
    h_instance: reaper_low::raw::HINSTANCE,
    rec: *mut reaper_low::raw::reaper_plugin_info_t,
) -> std::os::raw::c_int {
    let static_context = reaper_low::static_plugin_context();
    // SAFETY: `h_instance`/`rec` are exactly what REAPER passed to this entry
    // point; `bootstrap_extension_plugin` documents that an invalid pointer
    // may crash REAPER, but these come from REAPER itself (or null `rec`,
    // which it maps to clean failure `0`). `plugin_main` upholds the
    // `fn(PluginContext) -> Result<_, Box<dyn Error>>` contract below.
    unsafe { reaper_low::bootstrap_extension_plugin(h_instance, rec, static_context, plugin_main) }
}

// ---------------------------------------------------------------------------
// Smoke action definition (pure, unit-testable surface).
// ---------------------------------------------------------------------------

/// Bridge version reported at load (crate version; no paths, per §8脱敏).
pub const EXTENSION_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Stable command name for the smoke action (globally unique, survives
/// sessions; cf. `CommandId` docs in `main/medium/src/misc_newtypes.rs:31`).
pub const SMOKE_COMMAND_NAME: &str = "SynthLM_TestPing";

/// Action-list description (states the harmlessness contract up front).
pub const SMOKE_ACTION_DESC: &str = "SynthLM: test ping (writes %TEMP% marker, touches no project)";

/// Marker file name inside `%TEMP%` (scratch dir, never the project).
pub const SMOKE_MARKER_FILE_NAME: &str = "synthlm_ext_smoke.txt";

/// Command ID assigned by REAPER at load; `0` = not registered yet (`0` is
/// never a valid command ID — `CommandId::is_valid`, misc_newtypes.rs:58).
///
/// `HookCommand::call` is a static method with no `self`, so the ID must live
/// in a static. `Relaxed` suffices: written once on the main thread at load,
/// read on the main thread at action-dispatch time.
static SMOKE_COMMAND_ID: AtomicU32 = AtomicU32::new(0);

/// Joins the marker file name onto a temp dir (pure helper for tests).
#[must_use]
pub fn smoke_marker_path(temp_dir: &Path) -> PathBuf {
    temp_dir.join(SMOKE_MARKER_FILE_NAME)
}

/// Builds the marker file body (desensitised: version + epoch only).
///
/// `epoch_secs` comes from [`now_epoch_secs`]; taking it as a parameter keeps
/// this function pure and golden-testable.
#[must_use]
pub fn smoke_marker_text(version: &str, epoch_secs: u64) -> String {
    format!("synthlm-bridge ext smoke ok\nversion: {version}\nepoch_secs: {epoch_secs}\n")
}

/// Current Unix-epoch seconds (marker timestamp; falls back to `0` when the
/// clock is before the epoch instead of panicking).
#[must_use]
pub fn now_epoch_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Writes `text` to `path`, creating or truncating it.
pub fn write_marker_at(path: &Path, text: &str) -> io::Result<()> {
    std::fs::write(path, text)
}

/// Writes the smoke marker into `%TEMP%` and returns its path.
///
/// The marker proves the extension loaded and its action dispatched, without
/// touching any project state.
pub fn write_smoke_marker() -> io::Result<PathBuf> {
    let path = smoke_marker_path(&std::env::temp_dir());
    let text = smoke_marker_text(EXTENSION_VERSION, now_epoch_secs());
    write_marker_at(&path, &text)?;
    Ok(path)
}

/// Pure predicate behind [`SmokePing::call`]: `true` iff `candidate` is the
/// registered smoke command (`stored == 0` means "not registered yet").
#[must_use]
pub fn is_smoke_command(stored: u32, candidate: CommandId) -> bool {
    stored != 0 && candidate.get() == stored
}

/// The harmless test action: writes the `%TEMP%` marker, ignores anything else.
///
/// Returns `true` (handled) only for our own command ID so unrelated actions
/// keep flowing to their owners.
#[derive(Debug)]
pub struct SmokePing;

impl HookCommand for SmokePing {
    fn call(command_id: CommandId, _flag: i32) -> bool {
        if !is_smoke_command(SMOKE_COMMAND_ID.load(Ordering::Relaxed), command_id) {
            return false;
        }
        // Best-effort: the marker is evidence, not a transaction. A failure
        // still counts as handled so REAPER doesn't route our ID elsewhere.
        let _ = write_smoke_marker();
        true
    }
}

// ---------------------------------------------------------------------------
// Extension initialisation (called once by `ReaperPluginEntry` via bootstrap).
// ---------------------------------------------------------------------------

/// Loads the medium-level session, logs the version, and registers the smoke
/// action. Returns `Err` (→ entry returns `0` → clean unload) when any
/// registration fails.
///
/// The session owns the `gaccel`/`command` registrations and would unregister
/// them on `Drop` (`main/medium/src/reaper_session.rs:1357`); it is therefore
/// intentionally process-lifetime (`mem::forget`), matching the extension
/// lifetime (loaded at REAPER start, unloaded at quit — `README.md:197`).
/// This leaks exactly one session struct for the process duration, which is
/// the standard shape for REAPER extensions (the upstream test extension
/// keeps its high-level `Reaper` singleton alive the same way).
pub fn plugin_main(context: PluginContext) -> Result<(), Box<dyn Error>> {
    let mut session = ReaperSession::load(context);
    session.reaper().show_console_msg(format!(
        "SynthLM bridge {EXTENSION_VERSION} loaded (control-plane only, no project touched)\n"
    ));
    let command_id = session.plugin_register_add_command_id(SMOKE_COMMAND_NAME)?;
    SMOKE_COMMAND_ID.store(command_id.get(), Ordering::Relaxed);
    session.plugin_register_add_gaccel(OwnedGaccelRegister::without_key_binding(
        command_id,
        SMOKE_ACTION_DESC,
    ))?;
    session.plugin_register_add_hook_command::<SmokePing>()?;
    std::mem::forget(session);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn marker_path_joins_file_name() {
        let dir = Path::new("/tmp");
        assert_eq!(
            smoke_marker_path(dir),
            Path::new("/tmp/synthlm_ext_smoke.txt")
        );
    }

    #[test]
    fn marker_text_is_desensitised_and_stable() {
        let text = smoke_marker_text("0.0.0", 1_700_000_000);
        assert_eq!(
            text,
            "synthlm-bridge ext smoke ok\nversion: 0.0.0\nepoch_secs: 1700000000\n"
        );
        // No paths of any kind leak into the marker.
        assert!(!text.contains(":\\") && !text.contains(":/"));
    }

    #[test]
    fn smoke_command_predicate() {
        let id = CommandId::new(50_001);
        assert!(!is_smoke_command(0, id)); // not registered yet
        assert!(is_smoke_command(50_001, id));
        assert!(!is_smoke_command(50_001, CommandId::new(50_002)));
    }

    #[test]
    fn hook_ignores_foreign_commands_without_touching_fs() {
        // Unset static (0) + foreign ID → false, and no marker side effect is
        // possible on this path (returns before any I/O).
        assert!(!SmokePing::call(CommandId::new(59_999), 0));
    }

    #[test]
    fn marker_roundtrip_in_scratch_dir() {
        let dir = std::env::temp_dir().join("synthlm_ext_smoke_test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = smoke_marker_path(&dir);
        write_marker_at(&path, &smoke_marker_text("test", 1)).unwrap();
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "synthlm-bridge ext smoke ok\nversion: test\nepoch_secs: 1\n"
        );
        std::fs::remove_file(&path).unwrap();
    }

    #[test]
    fn epoch_secs_is_plausible() {
        // Past 2024-01-01; hard floor, not print-risky wall-clock assert.
        assert!(now_epoch_secs() > 1_704_067_200);
    }
}
